name: Build image and push to Docker Hub

on:
  workflow_run:
    workflows: ["Build project"]
    types:
      - completed
    branches:
      - "master" # todo change to test after creating prod env

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: docker sign-in
        run: echo $DOCKER_PASSWORD | docker login --username daneker --password-stdin
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t daneker/Coassemble-ui .

      - name: Push Docker image
        run: docker push daneker/Coassemble-ui
  deploy-to-server:
    runs-on: ubuntu-latest
    needs: build-docker-image
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd coassemble/test
            sudo docker rmi -f daneker/Coassemble-ui
            sudo docker compose down -v
            sudo docker compose up -d
